export const REQUEST_QUOTES_PENDING = 'REQUEST_QUOTES_PENDING';
export const REQUEST_QUOTES_SUCCESS = 'REQUEST_QUOTES_SUCCESS';
export const REQUEST_QUOTES_FAILED = 'REQUEST_QUOTES_FAILED';

export const GENERATE_COLOR = "GENERATE_COLOR";